// <auto-generated />
using System;
using Manager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Manager.Migrations
{
    [DbContext(typeof(ManagerContext))]
    partial class ManagerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ManagerInvoice.Models.Image", b =>
                {
                    b.Property<int>("A_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("A_ID"));

                    b.Property<DateTime>("A_CREATED_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("A_FILE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("H_ORDER_INT")
                        .HasColumnType("int");

                    b.Property<int>("H_ORDER_NO")
                        .HasColumnType("int");

                    b.HasKey("A_ID");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("ManagerInvoice.Models.Order", b =>
                {
                    b.Property<int>("H_ORDER_NO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("H_ORDER_NO"));

                    b.Property<string>("H_COMMENT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("H_CREATED_DATE")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("H_INVOICE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("H_INVOICE_NO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("H_INV_AMT")
                        .HasColumnType("int");

                    b.Property<int>("H_ORDER_INT")
                        .HasColumnType("int");

                    b.Property<string>("H_SECTOR_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("H_STATUS")
                        .HasColumnType("int");

                    b.Property<int>("H_STORE_NO")
                        .HasColumnType("int");

                    b.Property<string>("H_SUPP_COM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("H_SUPP_NO")
                        .HasColumnType("int");

                    b.Property<string>("H_SUP_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("H_TAX_NO")
                        .HasColumnType("int");

                    b.Property<string>("H_UPDATEBY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("H_UPDATED_DATE")
                        .HasColumnType("datetime2");

                    b.HasKey("H_ORDER_NO");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("ManagerInvoice.Models.OrderDetail", b =>
                {
                    b.Property<int>("DETAIL_ORDER_NO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DETAIL_ORDER_NO"));

                    b.Property<string>("D_ARTNAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("D_ART_DVT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("D_ART_NO")
                        .HasColumnType("int");

                    b.Property<string>("D_COMMENT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("D_GOLDVAT")
                        .HasColumnType("int");

                    b.Property<int>("D_GOLD_PRICE")
                        .HasColumnType("int");

                    b.Property<int>("D_LINE")
                        .HasColumnType("int");

                    b.Property<int>("D_MMUNT")
                        .HasColumnType("int");

                    b.Property<int>("D_ORDER_INT")
                        .HasColumnType("int");

                    b.Property<int>("D_ORDER_NO")
                        .HasColumnType("int");

                    b.Property<int>("D_QTY")
                        .HasColumnType("int");

                    b.Property<int>("D_STATUS")
                        .HasColumnType("int");

                    b.Property<int>("D_SUPVAT")
                        .HasColumnType("int");

                    b.Property<int>("D_SUP_PRICE")
                        .HasColumnType("int");

                    b.Property<string>("D_UPDATEBY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("H_CREATED_DATE")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("H_UPDATED_DATE")
                        .HasColumnType("datetime2");

                    b.HasKey("DETAIL_ORDER_NO");

                    b.ToTable("OrderDetail");
                });

            modelBuilder.Entity("ManagerInvoice.Models.ProgressOrder", b =>
                {
                    b.Property<int>("PO_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PO_ID"));

                    b.Property<string>("HISTORY_COMMIT_BY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HISTORY_CREATED_DATE")
                        .HasColumnType("datetime2");

                    b.Property<int>("HISTORY_ID")
                        .HasColumnType("int");

                    b.Property<int>("HISTORY_STATUS")
                        .HasColumnType("int");

                    b.Property<int>("H_ORDER_INT")
                        .HasColumnType("int");

                    b.Property<int>("H_ORDER_NO")
                        .HasColumnType("int");

                    b.HasKey("PO_ID");

                    b.ToTable("ProgressOrder");
                });

            modelBuilder.Entity("ManagerInvoice.Models.Sector", b =>
                {
                    b.Property<int>("H_SECTOR_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("H_SECTOR_ID"));

                    b.Property<DateTime>("CREATED_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("EMAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("H_SECTOR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UPDATED_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("UPDATE_BY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("H_SECTOR_ID");

                    b.ToTable("Sector");
                });
#pragma warning restore 612, 618
        }
    }
}
